version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - attach_workspace:
            at: /tmp/workspace
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
            - v1-node-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-dependencies-{{ checksum "package.json" }}
      - run: npm rebuild node-sass
      - run: npm run dist
      - aws-s3/copy:
            from: public/build
            to: 's3://react-app-demo.firstvoices.io'
            arguments: |
              --recursive \
              --acl public-read \
              --cache-control "max-age=300"
workflows:
  version: 2
  everything:
    jobs:
      - build
